name: Deploy to Pages

on:
  workflow_dispatch:
  push:
    branches:
      - master
    paths:
      - "src/**"
      - "public/**"
      - "vue.config.js"
      - ".github/workflows/pages-deploy.yml"

jobs:
  build:
    if: "!contains(toJSON(github.event.commits.*.message), '--skip-ci')"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install Dependencies
        run: yarn install --frozen-lockfile
      - name: Lint
        run: yarn run lint
      - name: Build
        run: yarn run build
        env:
          VUE_APP_SHA: ${{ github.sha }}
          VUE_APP_HTTPS: ${{ secrets.HTTPS }}
          VUE_APP_GTAG: ${{ secrets.GTAG }}
          VUE_APP_CDN: ${{ secrets.CDN }}
          USE_CDN: ${{ secrets.USE_CDN }}
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: "./dist"
  deploy:
    needs: build
    runs-on: ubuntu-latest
    concurrency:
      group: "pages"
      cancel-in-progress: true
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1
